package se.inera.intyg.minaintyg.integration.webcert.client.dto.value;

public enum CertificateDataValueType {
  BOOLEAN, TEXT, DATE, DATE_LIST, DATE_RANGE, DATE_RANGE_LIST, CODE_LIST, CODE, DIAGNOSIS_LIST, DIAGNOSIS, ICF, UNKOWN, UNCERTAIN_DATE,
  CAUSE_OF_DEATH_LIST, MEDICAL_INVESTIGATION_LIST, MEDICAL_INVESTIGATION, VISUAL_ACUITIES, DOUBLE, VISUAL_ACUITY, VIEW_TEXT,
  VIEW_LIST, VIEW_TABLE, VIEW_ROW, YEAR, INTEGER, CAUSE_OF_DEATH
}
