---

- name: Copy git-crypt key
  copy: src="{{ gitcrypt_key_file }}"
       dest="{{ inera_root }}/{{ gitcrypt_key_name }}"

- name: Unlock config repo
  command: /usr/local/bin/git-crypt unlock {{ inera_root }}/{{ gitcrypt_key_name }} chdir={{ config_folder }} 
  args:
    creates: "{{ config_folder }}/.git/git-crypt"
