---

- name: Copy git-crypt key
  copy:
    src: "{{ gitcrypt_key_file }}"
    dest: "{{ inera_root }}/{{ gitcrypt_key_name }}"

- name: Unlock config repo
  command: "/usr/local/bin/git-crypt unlock {{ inera_root }}/{{ gitcrypt_key_name }}"
  args:
    creates: "{{ config_folder }}/.git/git-crypt"
    chdir: {{ config_folder }}
