---
# file: roles/app-resources/tasks/main.yml

- name: delete application resources folder
  file: "state=absent path={{ app_resources_folder }}"

- name: create application resources folder
  file: "state=directory path={{ app_resources_folder }}"

- name: copy application resources
  copy: src="{{ app_resources_src }}"
       dest="{{ app_resources_folder }}"
