---

- name: Remove refdata
  shell: rm -f {{ tomcat_lib }}/refdata*.jar

- name: Get latest refdata version
  shell: curl -s https://build-inera.nordicmedtest.se/nexus/repository/public/se/inera/intyg/refdata/refdata/maven-metadata.xml | grep '<latest>.*</latest>' | sed 's/.*<latest>\(.*\)<\/latest>.*/\1/g'
  register: latest_refdata

- name: Download refdata-{{ latest_refdata.stdout }}.jar
  get_url: url=https://build-inera.nordicmedtest.se/nexus/repository/public/se/inera/intyg/refdata/refdata/{{ latest_refdata.stdout }}/refdata-{{ latest_refdata.stdout }}.jar
    dest={{ tomcat_lib }}

- name: Download javax.servlet.jsp.jstl-api-1.2.1.jar
  get_url:
    url: http://repo1.maven.org/maven2/javax/servlet/jsp/jstl/javax.servlet.jsp.jstl-api/1.2.1/javax.servlet.jsp.jstl-api-1.2.1.jar
    dest: "{{ tomcat_lib }}/javax.servlet.jsp.jstl-api-1.2.1.jar"
    
- name: Download javax.servlet.jsp.jstl-1.2.1.jar
  get_url:
    url: http://repo1.maven.org/maven2/org/glassfish/web/javax.servlet.jsp.jstl/1.2.1/javax.servlet.jsp.jstl-1.2.1.jar
    dest: "{{ tomcat_lib }}/javax.servlet.jsp.jstl-1.2.1.jar"
