---

- name: Download javax.servlet.jsp.jstl-api-1.2.1.jar
  get_url: url=http://repo1.maven.org/maven2/javax/servlet/jsp/jstl/javax.servlet.jsp.jstl-api/1.2.1/javax.servlet.jsp.jstl-api-1.2.1.jar
           dest={{ tomcat_lib }}
    
- name: Download javax.servlet.jsp.jstl-1.2.1.jar
  get_url: url=http://repo1.maven.org/maven2/org/glassfish/web/javax.servlet.jsp.jstl/1.2.1/javax.servlet.jsp.jstl-1.2.1.jar 
           dest={{ tomcat_lib }}
    
    