---

- name: Remove refdata
  shell: rm -f {{ tomcat_lib }}/refdata*.jar

- name: Download refdata
  get_url: url=https://build-inera.nordicmedtest.se/nexus/repository/public/se/inera/intyg/refdata/refdata/1.0.0.11/refdata-1.0.0.11.jar
           dest={{ tomcat_lib }}

- name: Download javax.servlet.jsp.jstl-api-1.2.1.jar
  get_url:
    url: http://repo1.maven.org/maven2/javax/servlet/jsp/jstl/javax.servlet.jsp.jstl-api/1.2.1/javax.servlet.jsp.jstl-api-1.2.1.jar
    dest: "{{ tomcat_lib }}/javax.servlet.jsp.jstl-api-1.2.1.jar"
    
- name: Download javax.servlet.jsp.jstl-1.2.1.jar
  get_url:
    url: http://repo1.maven.org/maven2/org/glassfish/web/javax.servlet.jsp.jstl/1.2.1/javax.servlet.jsp.jstl-1.2.1.jar
    dest: "{{ tomcat_lib }}/javax.servlet.jsp.jstl-1.2.1.jar"
