<?xml version="1.0" encoding="UTF-8" ?>
<!--
 Licensed to the Apache Software Foundation (ASF) under one
 or more contributor license agreements. See the NOTICE file
 distributed with this work for additional information
 regarding copyright ownership. Sveriges Kommuner och Landsting licenses this file
 to you under the Apache License, Version 2.0 (the
 "License"); you may not use this file except in compliance
 with the License. You may obtain a copy of the License at

 http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing,
 software distributed under the License is distributed on an
 "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 KIND, either express or implied. See the License for the
 specific language governing permissions and limitations
 under the License.
 -->
<wsdl:definitions name='GetConsentInteraction'
  xmlns:wsdl='http://schemas.xmlsoap.org/wsdl/'
  xmlns:soap='http://schemas.xmlsoap.org/wsdl/soap/'
  xmlns:xs='http://www.w3.org/2001/XMLSchema'
  xmlns:tjsr='urn:riv:insuranceprocess:healthreporting:GetConsentResponder:1'
  xmlns:tjsi='urn:riv:insuranceprocess:healthreporting:GetConsentInitiator:1'
  xmlns:tns='urn:riv:insuranceprocess:healthreporting:GetConsent:1:rivtabp20'
  targetNamespace='urn:riv:insuranceprocess:healthreporting:GetConsent:1:rivtabp20'
  xmlns:wsa="http://www.w3.org/2005/08/addressing"
  >

  <xs:annotation>
    <xs:documentation>
      Tjänsteinteraktionens namn: GetConsentInteraction
      Beskrivning: 
       Hämta status om medgivande (consent) givits för medborgarne om att intyg får hanteras elektroniskt.
      Revisioner: 
        2012-08-09: Initial version (Marcus Krantz and Roger Lindsjö, Callista Enterprise AB)
      Tjänstedomän: insuranceprocess:healthreporting
      Tjänsteinteraktionstyp: Fråga-Svar
      WS-profil: RIVTABP21
      Förvaltas av: Sveriges Kommuner och Landsting
    </xs:documentation>
  </xs:annotation>

  <wsdl:types>
    <xs:schema targetNamespace='urn:riv:insuranceprocess:healthreporting:GetConsent:1:rivtabp20'>
      <xs:import schemaLocation='GetConsentResponder_1.0.xsd' namespace='urn:riv:insuranceprocess:healthreporting:GetConsentResponder:1' />
      <xs:import schemaLocation='../../core_components/ws-addressing-1.0.xsd' namespace='http://www.w3.org/2005/08/addressing' />
    </xs:schema>
  </wsdl:types>

  <wsdl:message name='GetConsentRequest'>
    <wsdl:part name='LogicalAddress' element='wsa:To'>
      <wsdl:documentation>The organisation number of the receiving insurance institution</wsdl:documentation>
    </wsdl:part>
    <wsdl:part name='parameters' element='tjsr:GetConsentRequest' />
  </wsdl:message>

  <wsdl:message name='GetConsentResponse'>
    <wsdl:part name='parameters' element='tjsr:GetConsentResponse' />
  </wsdl:message>

  <wsdl:portType name='GetConsentResponderInterface'>
    <wsdl:operation name='GetConsent'>
      <wsdl:input message='tns:GetConsentRequest' />
      <wsdl:output message='tns:GetConsentResponse' />
    </wsdl:operation>
  </wsdl:portType>

  <wsdl:binding name='GetConsentResponderBinding' type='tns:GetConsentResponderInterface'>
    <soap:binding style='document' transport='http://schemas.xmlsoap.org/soap/http' />
    <wsdl:operation name='GetConsent'>
      <soap:operation soapAction='urn:riv:insuranceprocess:healthreporting:GetConsentResponder:1:GetConsent' style='document' />
      <wsdl:input>
        <soap:header use='literal' message='tns:GetConsentRequest' part='LogicalAddress' />
        <soap:body use='literal' parts='parameters' />
      </wsdl:input>
      <wsdl:output>
        <soap:body use='literal' />
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>

  <wsdl:service name='GetConsentResponderService'>
    <wsdl:port name='GetConsentResponderPort' binding='tns:GetConsentResponderBinding'>
      <soap:address location='http://tempuri.org' />
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
