spring:
  security:
    filter:
      dispatcher-types: async, error, request, forward
    saml2:
      relyingparty:
        registration:
          one:
            signing.credentials:
              - private-key-location: classpath:credentials/rp-private.key
                certificate-location: classpath:credentials/rp-certificate.crt
            assertingparty.metadata-uri: https://m00-mg-local.testidp.funktionstjanster.se/samlv2/idp/metadata/0/30
            slo:
              location: /logout/saml2/slo # RelyingPartyRegistration::singleLogoutServiceLocation
              response-location: /logout/saml2/slo # RelyingPartyRegistration::singleLogoutServiceResponseLocation
              binding: POST # RelyingPartyRegistration::singleLogoutServiceBinding
            singlelogout:
              binding: POST
              url: "https://m00-mg-local.testidp.funktionstjanster.se/samlv2/idp/sloreq/0/30?mgvhostparam=0"
              responseUrl: "https://m00-mg-local.testidp.funktionstjanster.se/samlv2/idp/sloreq/0/30?mgvhostparam=0"
              sign-request: false
            acs:
              location: "{baseUrl}/saml/SSO"

