<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions 
	name="RegistreraIntygInteraction"
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" 
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" 
	xmlns:http="http://schemas.xmlsoap.org/wsdl/http/" 
	xmlns:xs="http://www.w3.org/2001/XMLSchema"
	xmlns:i="urn:intyg:common-model:1"
	xmlns:tns="urn:intyg:RegistreraIntyg:1"
	targetNamespace="urn:intyg:RegistreraIntyg:1">

	<wsdl:types>
	  <xs:schema>
        <xs:import schemaLocation="intyg_common_model.xsd" namespace="urn:intyg:common-model:1"/>
      </xs:schema>
	</wsdl:types>

	<wsdl:message name="RegistreraIntygRequest">
		<wsdl:part name="intyg" element="i:utlatande" />
	</wsdl:message>

	<wsdl:message name="RegistreraIntygResponse">
		<wsdl:part name="intyg" element="i:utlatande"/>
	</wsdl:message>

	<wsdl:portType name="RegistreraIntygResponderInterface">
	
		<wsdl:operation name="RegistreraIntyg">
			<wsdl:input message="tns:RegistreraIntygRequest"/>
			<wsdl:output message="tns:RegistreraIntygResponse"/>
		</wsdl:operation>
		
	</wsdl:portType>
	
	<wsdl:binding name="RegistreraIntygResponderBinding" type="tns:RegistreraIntygResponderInterface">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>

		<wsdl:operation name="RegistreraIntyg">
			<soap:operation soapAction="urn:intyg:RegistreraIntygResponder:1"/>
			<wsdl:input>
				<soap:body use="literal" parts="intyg"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal" parts="intyg"/>
			</wsdl:output>
		</wsdl:operation>

	</wsdl:binding>

	<wsdl:service name="RegistreraIntygResponderService">
		<wsdl:port name="RegistreraIntygResponderPort" binding="tns:RegistreraIntygResponderBinding">
			<soap:address location="http://tempuri.org"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>
