apiVersion: v1
data:
  CERTIFICATE_BASEURL: http://intygstjanst:8080
  FK_SAML_KEYSTORE_ALIAS: minaintyg.se
  FK_SAML_KEYSTORE_FILE: file://${certificate.folder}/fk-saml-keystore.jks
  NTJP_WS_CERTIFICATE_FILE: ${certificate.folder}/minaintyg.sjunet.org.p12
  NTJP_WS_CERTIFICATE_TYPE: PKCS12
  NTJP_WS_TRUSTSTORE_FILE: ${certificate.folder}/truststore-mvk-sso.jks
  NTJP_WS_TRUSTSTORE_TYPE: JKS
  REDIS_SENTINEL_MASTER_NAME: ind-pint-redis
  REDIS_SERVICE_HOST: ind-pint-redis1.ind1.sth.basefarm.net;ind-pint-redis2.ind1.sth.basefarm.net;ind-pint-redis3.ind1.sth.basefarm.net
  REDIS_SERVICE_PORT: 26379;26379;26379
  REFDATA_URL: file://localhost/opt/minaintyg/env/refdata-1.0.0.67.jar
  RESOURCES_FOLDER: 'classpath:'
kind: ConfigMap
metadata:
  creationTimestamp: 2019-04-16T17:51:34Z
  name: minaintyg-configmap-envvar
  namespace: pintyg
  resourceVersion: "76017805"
  selfLink: /api/v1/namespaces/pintyg/configmaps/minaintyg-configmap-envvar
  uid: 46780f99-6070-11e9-935a-005056a1387d
