apiVersion: v1
stringData:
  NTJP_WS_CERTIFICATE_PASSWORD: xxxxxxx
  NTJP_WS_KEY_MANAGER_PASSWORD: xxxxxxx
  NTJP_WS_TRUSTSTORE_PASSWORD: xxxxxxx
  MVK_KEYSTORE_PASSWORD: xxxxxxx
  MVK_KEYSTORE_KEYPASSWORD: xxxxxxx
  MVK_TRUSTSTORE_PASSWORD: xxxxxxx
  FK_SAML_KEYSTORE_PASSWORD: xxxxxxx
kind: Secret
metadata:
  name: minaintyg-secret-envvar
type: Opaque
