apiVersion: v1
data:
  minaintyg.links.json: |
    [
      {
        "key": "patientdatalagen",
        "url": "https://www.riksdagen.se/sv/Dokument-Lagar/Lagar/Svenskforfattningssamling/Patientdatalag-2008355_sfs-2008-355/?bet=2008:355",
        "text": "Patientdatalagen (PDL)",
        "target": "_blank"
      },
      {
        "key": "diPatientDataLagen",
        "url": "https://www.datainspektionen.se/lagar-och-regler/patientdatalagen",
        "text": "Läs mer om lagring av uppgifter och ändring av information hos Datainspektionen",
        "target": "_blank"
      },
      {
        "key": "ptsCookiesModal",
        "url": "https://www.pts.se/sv/Privat/Internet/Skydd-av-uppgifter/Fragor-och-svar-om-kakor-for-anvandare1/",
        "text": "Kommunikationsmyndigheten PTS sida om kakor",
        "target": "_blank"
      },
      {
        "key": "personuppgiftslagen",
        "url": "https://www.riksdagen.se/sv/Dokument-Lagar/Lagar/Svenskforfattningssamling/Personuppgiftslag-1998204_sfs-1998-204/?bet=1998:204",
        "text": "Personuppgiftslagen (PUL)",
        "target": "_blank"
      },
      {
        "key": "pul48",
        "url": "https://www.riksdagen.se/sv/dokument-lagar/dokument/svensk-forfattningssamling/personuppgiftslag-1998204_sfs-1998-204",
        "text": "48 § PUL",
        "target": "_blank"
      },
      {
        "key": "ptsCookies",
        "url": "https://www.pts.se/sv/Privat/Internet/Skydd-av-uppgifter/Fragor-och-svar-om-kakor-for-anvandare1/",
        "text": "Post- och telestyrelsens webbplats (extern länk).",
        "target": "_blank"
      },
      {
        "key": "ptsCookiesBanner",
        "url": "https://www.pts.se/sv/Privat/Internet/Skydd-av-uppgifter/Fragor-och-svar-om-kakor-for-anvandare1/",
        "text": "Post- och telestyrelsens webbplats",
        "target": "_blank"
      },
      {
        "key": "ptsCookiesMerOm",
        "url": "https://www.pts.se/sv/Privat/Internet/Skydd-av-uppgifter/Fragor-och-svar-om-kakor-for-anvandare1/",
        "text": "Mer om kakor (cookies) på Post- och telestyrelsens webbplats",
        "target": "_blank"
      },
      {
        "key": "ineraStartsida",
        "url": "https://www.inera.se",
        "text": "Inera AB (extern länk)",
        "target": "_blank"
      },
      {
        "key": "ineraExternalLink",
        "url": "https://www.inera.se",
        "text": "www.inera.se",
        "target": "_blank"
      },
      {
        "key": "ineraAb",
        "url": "https://www.inera.se",
        "text": "Inera AB",
        "target": "_blank"
      },
      {
        "key": "ineraKontakt",
        "url": "https://www.inera.se/kontakt",
        "text": "Hjälp och support",
        "target": "_blank"
      },
      {
        "key": "ineraKundserviceKontakt",
        "url": "https://www.inera.se/kundservice",
        "text": "Ineras kundservice",
        "target": "_blank"
      },
      {
        "key": "ineraKundserviceFelanmalan",
        "url": "https://www.inera.se/felanmalan",
        "text": "Kontaktinformation till kundservice (extern länk)",
        "target": "_blank"
      },
      {
        "key": "ineraKundserviceAnmalFel",
        "url": "https://www.inera.se/felanmalan",
        "text": "Ineras kundservice",
        "target": "_blank"
      },
      {
        "key": "merInfoElegMvk",
        "url": "https://www.1177.se/Tema/E-tjanster/Om-1177-Vardguidens-e-tjanster/Sa-loggar-du-in/",
        "text": "Mer information om hur du skaffar en e-legitimation.",
        "target": "_blank"
      },
      {
        "key": "1177etjanster",
        "url": "https://www.1177.se/e-tjanster",
        "text": "1177.se/e-tjanster",
        "target": "_blank"
      },
      {
        "key": "1177etjanster2",
        "url": "https://www.1177.se/e-tjanster",
        "text": "www.1177.se",
        "target": "_blank"
      },
      {
        "key": "forsakringskassan",
        "url": "https://www.forsakringskassan.se",
        "text": "Försäkringskassan",
        "target": "_blank"
      },
      {
        "key": "skatteverketSekretessmarkeradePersonuppgifter",
        "url": "https://www.skatteverket.se/privat/folkbokforing/skyddadepersonuppgifter/hanteringavsekretessmarkeradepersonuppgifter.4.18e1b10334ebe8bc80002541.html",
        "text": "här",
        "target": "_blank"
      },
      {
        "key": "ivo",
        "url": "https://www.ivo.se/Sidor/default.aspx",
        "text": "Inspektionen för vård och omsorg, IVO",
        "target": "_blank"
      },
      {
        "key": "1177uppgifterSkyddasHanteras",
        "url": "https://www.1177.se/Tema/E-tjanster/Om-1177-Vardguidens-e-tjanster/Sa-skyddas-och-hanteras-dina-uppgifter-i-e-tjansterna/",
        "text": "Mer information om hantering av personuppgifter hos 1177 Vårdguiden",
        "target": "_blank"
      },
      {
        "key": "1177patientjournalen",
        "url": "https://www.1177.se/Regler-och-rattigheter/Patientjournalen/",
        "text": "Mer information om patientjournalen hos 1177.se",
        "target": "_blank"
      },
      {
        "key": "adobeReader",
        "url": "https://get.adobe.com/reader/?loc=se",
        "text": "Adobe Reader",
        "target": "_blank"
      },
      {
        "key": "forsakringskassan-sjuk",
        "url": "https://www.forsakringskassan.se/sjuk",
        "text": "www.forsakringskassan.se/sjuk",
        "target": "_blank"
      }
    ]
kind: ConfigMap
metadata:
  name: minaintyg-resources-links
