apiVersion: v1
data:
  minaintyg-logback.xml: |
    <?xml version="1.0" encoding="UTF-8"?>
    <!-- Copyright (C) 2013 Inera AB (http://www.inera.se) This file is part
      of Inera Certificate Web (http://code.google.com/p/inera-certificate-web).
      Inera Certificate Web is free software: you can redistribute it and/or modify
      it under the terms of the GNU Affero General Public License as published
      by the Free Software Foundation, either version 3 of the License, or (at
      your option) any later version. Inera Certificate Web is distributed in the
      hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied
      warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
      GNU Affero General Public License for more details. You should have received
      a copy of the GNU Affero General Public License along with this program.
      If not, see <http://www.gnu.org/licenses/>. -->
    <configuration scan="true" scanPeriod="30 seconds">

      <jmxConfigurator />

      <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
        <filter class="se.inera.intyg.common.util.logging.MarkerFilter">
          <markers>Monitoring</markers>
          <onMatch>DENY</onMatch>
          <onMismatch>ACCEPT</onMismatch>
        </filter>
        <layout class="ch.qos.logback.classic.PatternLayout">
          <Pattern>%date{ISO8601} [%thread] %-5level %logger{36} - %msg%n
          </Pattern>
        </layout>
      </appender>

      <!--Daily rolling file appender -->
      <appender name="FILE" class="ch.qos.logback.core.rolling.RollingFileAppender">
        <filter class="se.inera.intyg.common.util.logging.MarkerFilter">
          <markers>Monitoring</markers>
            <onMatch>DENY</onMatch>
          <onMismatch>ACCEPT</onMismatch>
        </filter>
        <file>${catalina.base}/logs/minaintyg.log</file>
        <rollingPolicy class="ch.qos.logback.core.rolling.TimeBasedRollingPolicy">
          <fileNamePattern>${catalina.base}/logs/minaintyg.%d{yyyy-MM-dd}.log
          </fileNamePattern>
        </rollingPolicy>
        <encoder>
          <pattern>%date{ISO8601} [%thread] %-5level %logger{36} - %msg%n
          </pattern>
        </encoder>
      </appender>

      <!--Daily rolling file appender for logging monitoring events -->
      <appender name="MONITORING" class="ch.qos.logback.core.rolling.RollingFileAppender">
        <filter class="se.inera.intyg.common.util.logging.MarkerFilter">
          <marker>Monitoring</marker>
          <onMatch>ACCEPT</onMatch>
          <onMismatch>DENY</onMismatch>
        </filter>
        <file>${catalina.base}/logs/minaintyg-monitoring.log</file>
        <rollingPolicy class="ch.qos.logback.core.rolling.TimeBasedRollingPolicy">
          <fileNamePattern>${catalina.base}/logs/minaintyg-monitoring.%d{yyyy-MM-dd}.log
          </fileNamePattern>
        </rollingPolicy>
        <encoder class="ch.qos.logback.core.encoder.LayoutWrappingEncoder">
          <layout class="se.inera.intyg.minaintyg.web.logging.PatternLayoutWithSessionContext">
            <param name="Pattern" value="%date{ISO8601} %session - %msg%n"/>
          </layout>
        </encoder>
      </appender>

      <logger name="org.springframework" level="WARN" />
      <logger name="org.springframework.security" level="WARN" />
      <logger name="org.springframework.core.env.PropertySourcesPropertyResolver" level="WARN" />
      <logger name="org.springframework.web" level="WARN" />
      <logger name="org.springframework.http" level="WARN" />

      <logger name="org.apache.cxf" level="error" />

      <logger name="se.inera.intyg.minaintyg.web" level="WARN" />
      <logger name="se.inera.intyg.minaintyg.web.service.MonitoringLogService" level="INFO" />

      <root level="WARN">
        <appender-ref ref="STDOUT" />
        <appender-ref ref="FILE" />
        <appender-ref ref="MONITORING" />
      </root>

    </configuration>

  minaintyg.properties: >

    # Configuration folder

    config.dir = ${minaintyg.config.folder}



    # Host URLs

    intygstjanst.host.url = http://intygstjanst:8080

    intygstjanst.secure.host.url = http://intygstjanst:8080

    # Note, we may add /inera-certificate as suffix to the above lines in case we deploy intygstjansten under that context path again.

    #################################################

    #

    # Services provided by Intygstjansten

    #

    #################################################

    consent.get.url = ${intygstjanst.host.url}/get-consent/v1.0

    consent.set.url = ${intygstjanst.host.url}/set-consent/v1.0

    certificates.list.v3.url = ${intygstjanst.secure.host.url}/list-certificates-for-citizen/v3.0

    certificates.setcertificatestatus-rivta.url = ${intygstjanst.secure.host.url}/set-certificate-status-rivta/v2.0

    certificates.sendcertificatetorecipient.url = ${intygstjanst.secure.host.url}/send-certificate-to-recipient/v2.0

    certificates.getcertificate.url = ${intygstjanst.secure.host.url}/get-certificate-se/v2.0

    certificates.getrecipientforcertificate.url = ${intygstjanst.host.url}/get-recipients-for-certificate/v1.0

    certificates.pingforconfiguration.url = ${intygstjanst.secure.host.url}/ping-for-configuration/v1.0

    certificates.getmedicalcertificate.endpoint.url = ${intygstjanst.host.url}/get-medical-certificate/v1.0

    certificates.gettsbas.endpoint.url = ${intygstjanst.host.url}/get-ts-bas/v1.0

    certificates.gettsdiabetes.endpoint.url = ${intygstjanst.host.url}/get-ts-diabetes/v1.0

    certificates.listknownrecipients.url = ${intygstjanst.host.url}/list-known-recipients/v1.0

    certificates.listrelationsforcertificate.url = ${intygstjanst.host.url}/list-relations-for-certificate/v1.0



    # Expression for configuring <http:conduit>

    mi.ntjp.conduit.name.expression=



    #################################################

    #

    # SAML config

    #

    #################################################



    # The application's logout URL, either /web/logga-ut for dev and test, or /saml/logout for demo, qa and prod

    application.logout.url = /web/logga-ut



    # 1177 Login properties

    elva77.url.main = https://kontakt.minavardkontakter.se/mvk/

    elva77.url.login = /saml/login/alias/eleg

    elva77.url.logout = /error.jsp?reason=logout



    fk.saml.keystore.file = file:${config.dir}/certifikat/fk-saml-keystore.jks

    fk.saml.keystore.alias = minaintyg.se

    fk.saml.successful.logout.url=/error.jsp?reason=logout



    # setting skew time to 5 minutes because autentiseringstjanst issues SAML tokens with issue date +1 minute in the future

    sakerhetstjanst.saml.responseSkew = 300







    ## These are legacy properties for FK SAML. These values should now exist in profile-specific versions of sp-fk.xml

    fk.entityId=https://qa.minaintyg.se/web/fksso/saml/SSO/alias/defaultAlias

    fk.saml.baseUrl = https://minaintyg.inera.nordicmedtest.se/web/fksso



    #################################################

    #

    # Dynamic texts

    #

    #################################################

    texts.file.directory=${minaintyg.resources.folder}/texts/

    texts.update.cron= 0 * * * * *



    #################################################

    #

    # Recipient update schedule

    #

    #################################################

    recipient.update.cron = 0 * * * * *



    #################################################

    #

    # PU ignite cache settings

    #

    #################################################

    cache.default.expiration.seconds=1440

    cache.ipaddresses=127.0.0.1:47550..47559

    cache.bindport=47550

    pu.cache.expiry=1440



    #################################################

    #

    # PU service

    #

    #################################################

    putjanst.logicaladdress = PUTEST

    putjanst.endpoint.url = http://localhost:${minaintyg.stubs.port}/services/pu



    ################################################

    #

    # NTjP WebService Configuration

    #

    ################################################

    ntjp.ws.certificate.file = ${config.dir}/certifikat/verifiering.webcert.intygstjanster.sjunet.org_autentisering.p12

    ntjp.ws.certificate.type = PKCS12

    ntjp.ws.truststore.file=${config.dir}/certifikat/truststore.jks

    ntjp.ws.truststore.type=JKS



    # Dynamic links

    dynamic.links.file=${minaintyg.resources.folder}/links/minaintyg.links.json



kind: ConfigMap
metadata:
  name: minaintyg-konfiguration-test
