---

- name: Stop tomcat
  service:
    name: "{{ tomcat_service }}"
    state: stopped
    pattern: "{{ tomcat_service }}"

- name: Create release directory
  file:
    path: "{{ releases_folder }}"
    state: directory

- name: Download minaintyg-web-{{ version }}.war
  get_url:
    url: "https://build-inera.nordicmedtest.se/nexus/repository/releases/se/inera/intyg/minaintyg/minaintyg-web/{{ version }}/minaintyg-web-{{ version }}.war"
    dest: "{{ releases_folder }}/minaintyg-web-{{ version }}.war"
    validate_certs: no
    timeout: 60
  when: deploy_from_repo|bool

- name: Copy minaintyg-web-{{ version }}.war
  copy:
    src: "{{ playbook_dir }}/../web/build/libs/minaintyg-web-{{ version }}.war"
    dest: "{{ releases_folder }}/minaintyg-web-{{ version }}.war"
  when: not deploy_from_repo|bool

- name: Remove old version of unpacked war
  file:
    state: absent
    path: "{{ webapps_folder }}/ROOT"

- name: Deploy minaintyg-web-{{ version }}.war as ROOT.war
  copy:
    src: "{{ releases_folder }}/minaintyg-web-{{ version }}.war"
    dest: "{{ webapps_folder }}/ROOT.war"
    remote_src: True

- name: Fetch configuration repo to get new branches
  command: git fetch origin
  args:
    chdir: "{{ config_folder }}"

- name: Update configuration to {{ config_version }}
  git:
    repo: "{{ config_repository }}"
    dest: "{{ config_folder }}"
    version: "{{ config_version }}"

- name: Start tomcat
  service:
    name: "{{ tomcat_service }}"
    state: restarted
    pattern: "{{ tomcat_service }}"
