---
# file: roles/minaintyg/tasks/main.yml

- name: stop tomcat
  service: name={{ tomcat_service }} state=stopped pattern=org.apache.catalina.startup.Bootstrap

- name: create release directory
  file: path={{ releases_folder }} state=directory

- name: Download minaintyg-web-{{ version }}.war
  get_url: url=https://build-inera.nordicmedtest.se/nexus/content/repositories/{{ repo }}/se/inera/intyg/minaintyg/minaintyg-web/{{ version }}/minaintyg-web-{{ version }}.war
           dest={{ releases_folder }}/minaintyg-web-{{ version }}.war
           validate_certs=no

- name: remove old version of unpacked war
  file: state=absent
      path={{ webapps_folder }}/ROOT

- name: remove old version of war
  file: state=absent
      path={{ webapps_folder }}/ROOT.war

- name: Deploy minaintyg-web-{{ version }}.war as ROOT.war
  command: cp {{ releases_folder }}/minaintyg-web-{{ version }}.war {{ webapps_folder }}/ROOT.war

- name: Create version file
  template: src=version.txt.j2 dest={{ webapps_folder }}/version.txt

- name: pull configuration repo to get new branches
  command: chdir={{ config_folder }} git pull origin

- name: update configuration to {{ config_version }}
  git: repo={{ config_repository }}
       dest={{ config_folder }}
       version={{ config_version }}

- name: start tomcat
  service: name={{ tomcat_service }} state=started pattern=org.apache.catalina.startup.Bootstrap
