---
# This playbook deploys Mina Intyg 

- hosts: tomcat
  serial: 1
  become: yes
  environment:
    "{{ proxy_env }}"
  vars:
    config_version: master

  roles:
    - app-resources
    - minaintyg

