package se.inera.certificate.model;

/**
 * @author andreaskaltenbach
 */
public enum Aktivitetskod {
    ARBETSLIVSINRIKTAD_REHABILITERING_AR_AKTUELL,
    ARBETSLIVSINRIKTAD_REHABILITERING_AR_EJ_AKTUELL,
    GAR_EJ_ATT_BEDOMMA_OM_ARBETSLIVSINRIKTAD_REHABILITERING_AR_AKTUELL,
    FORANDRAT_RESSATT_TILL_ARBETSPLATSEN_AR_AKTUELLT,
    FORANDRAT_RESSATT_TILL_ARBETSPLATSEN_AR_EJ_AKTUELLT,
    PLANERAD_ELLER_PAGAENDE_BEHANDLING_ELLER_ATGARD_INOM_SJUKVARDEN,
    PLANERAD_ELLER_PAGAENDE_ANNAN_ATGARD,
    KONTAKT_MED_FORSAKRINGSKASSAN_AR_AKTUELL,
    PATIENTEN_BEHOVER_FA_KONTAKT_MED_FORETAGSHALSOVARDEN,
    AVSTANGNING_ENLIGT_SM_L_PGA_SMITTA,
    OVRIGT,
    PATIENTEN_BEHOVER_FA_KONTAKT_MED_ARBETSFORMEDLINGEN
}
