package se.inera.intyg.minaintyg.integration.webcert.client.dto.config;

public enum CertificateDataConfigTypes {
  CATEGORY, UE_RADIO_BOOLEAN, UE_CHECKBOX_BOOLEAN, UE_CHECKBOX_MULTIPLE_DATE, UE_CHECKBOX_MULTIPLE_CODE, UE_RADIO_MULTIPLE_CODE,
  UE_RADIO_MULTIPLE_CODE_OPTIONAL_DROPDOWN, UE_DIAGNOSES, UE_CHECKBOX_DATE_RANGE_LIST, UE_TEXTAREA, UE_DROPDOWN, UE_ICF, UE_DATE,
  UE_UNCERTAIN_DATE, UE_MESSAGE, UE_TEXTFIELD, UE_TYPE_AHEAD, UE_HEADER, UE_CAUSE_OF_DEATH, UE_MEDICAL_INVESTIGATION,
  UE_VISUAL_ACUITY, UE_VIEW_TEXT, UE_VIEW_LIST, UE_VIEW_TABLE, UE_YEAR, UE_INTEGER, UE_DATE_RANGE, UE_CAUSE_OF_DEATH_LIST
}
